-- Replace partner passwords with server-issued, short-lived email sign-in links.
-- Existing password hashes and sessions are preserved during rollout; the
-- application no longer reads them. They can be removed after production
-- verification and explicit approval of the forced sign-out.

alter table public.partners
  alter column password_hash drop not null;

create table if not exists public.partner_magic_link_tokens (
  id bigint generated by default as identity primary key,
  partner_id integer not null references public.partners(id) on delete cascade,
  token_hash text not null unique
    check (token_hash ~ '^sha256:[0-9a-f]{64}$'),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  check (expires_at > created_at)
);

create index if not exists partner_magic_link_tokens_partner_id_idx
  on public.partner_magic_link_tokens (partner_id);
create index if not exists partner_magic_link_tokens_expires_at_idx
  on public.partner_magic_link_tokens (expires_at);

alter table public.partner_magic_link_tokens enable row level security;
revoke all privileges on table public.partner_magic_link_tokens from public, anon, authenticated;
revoke all privileges on sequence public.partner_magic_link_tokens_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.partner_magic_link_tokens to service_role;
grant usage, select on sequence public.partner_magic_link_tokens_id_seq to service_role;

create or replace function public.prune_partner_magic_links()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.partner_magic_link_tokens
  where ctid in (
    select ctid
    from public.partner_magic_link_tokens
    where expires_at <= pg_catalog.clock_timestamp()
       or consumed_at < pg_catalog.clock_timestamp() - interval '7 days'
    order by expires_at
    limit 100
  );
  return null;
end;
$$;

revoke all on function public.prune_partner_magic_links() from public, anon, authenticated;
grant execute on function public.prune_partner_magic_links() to service_role;

drop trigger if exists prune_partner_magic_links_after_insert
  on public.partner_magic_link_tokens;
create trigger prune_partner_magic_links_after_insert
after insert on public.partner_magic_link_tokens
for each statement execute function public.prune_partner_magic_links();

notify pgrst, 'reload schema';
