-- Organisation-scoped, expiring, hashed capabilities for the customer portal.
-- Replaces the permanent plaintext token historically stored on people.

create table if not exists public.customer_portal_tokens (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  person_id uuid not null references public.people(id) on delete cascade,
  token_hash text not null unique check (token_hash ~ '^sha256:[0-9a-f]{64}$'),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, person_id)
);

create index if not exists customer_portal_tokens_expires_at_idx
  on public.customer_portal_tokens (expires_at);

alter table public.customer_portal_tokens enable row level security;
revoke all on public.customer_portal_tokens from public, anon, authenticated;
grant all on public.customer_portal_tokens to service_role;
grant usage, select on sequence public.customer_portal_tokens_id_seq to service_role;

