/**
 * Stripe Webhook Handler — /api/stripe-webhook
 *
 * Listens for Stripe events and:
 *   - Verifies the webhook signature (HMAC-SHA256)
 *   - On payment_intent.succeeded: marks the order as deposit paid in Supabase
 *     and sends a payment confirmation email to the customer
 *
 * Setup in Stripe Dashboard → Developers → Webhooks:
 *   Endpoint URL : https://searsmelvin.co.uk/api/stripe-webhook
 *   Events       : payment_intent.succeeded, payment_intent.payment_failed
 *
 * Required env var (Cloudflare Pages → Settings → Environment Variables):
 *   STRIPE_WEBHOOK_SECRET  → "Signing secret" shown after creating the webhook endpoint
 */

const BUSINESS_NAME  = "Sears Melvin Memorials";
const BUSINESS_EMAIL = "info@searsmelvin.co.uk";
const FROM_EMAIL     = "info@searsmelvin.co.uk";

// ── Stripe webhook signature verification (Web Crypto API) ─────────────────────
async function verifyStripeSignature(rawBody, sigHeader, secret) {
  if (!sigHeader || !secret) return false;

  const parts     = sigHeader.split(",");
  const tPart     = parts.find(p => p.startsWith("t="));
  const v1Part    = parts.find(p => p.startsWith("v1="));
  if (!tPart || !v1Part) return false;

  const timestamp    = tPart.slice(2);
  const givenSig     = v1Part.slice(3);
  const signedPayload = `${timestamp}.${rawBody}`;

  // Reject events older than 5 minutes
  const age = Math.floor(Date.now() / 1000) - parseInt(timestamp, 10);
  if (age > 300) return false;

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sigBytes    = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signedPayload));
  const computedSig = Array.from(new Uint8Array(sigBytes))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");

  return computedSig === givenSig;
}

// ── Main handler ────────────────────────────────────────────────────────────────
export async function onRequestPost({ request, env }) {
  const rawBody    = await request.text();
  const sigHeader  = request.headers.get("stripe-signature") || "";
  const webhookSecret = env.STRIPE_WEBHOOK_SECRET || "";

  if (webhookSecret) {
    const valid = await verifyStripeSignature(rawBody, sigHeader, webhookSecret);
    if (!valid) {
      console.error("Stripe webhook signature verification failed");
      return new Response(JSON.stringify({ error: "Invalid signature" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }
  }

  let event;
  try {
    event = JSON.parse(rawBody);
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (event.type === "payment_intent.succeeded") {
    await handlePaymentSucceeded(env, event.data.object);
  }

  if (event.type === "payment_intent.payment_failed") {
    const pi  = event.data.object;
    const err = pi.last_payment_error?.message || "Unknown error";
    console.error(`Payment failed for PI ${pi.id}: ${err}`);
  }

  return new Response(JSON.stringify({ received: true }), {
    headers: { "Content-Type": "application/json" },
  });
}

// ── Payment succeeded ───────────────────────────────────────────────────────────
async function handlePaymentSucceeded(env, pi) {
  const { customer_name: name, customer_email: email, cemetery, product } = pi.metadata;
  const amountPaid = (pi.amount_received / 100).toFixed(2);
  const today      = new Date().toISOString().split("T")[0];

  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_KEY) {
    console.warn("Supabase not configured — skipping invoice/payment insert");
  } else {
    const sbHeaders = {
      "apikey":        env.SUPABASE_SERVICE_KEY,
      "Authorization": `Bearer ${env.SUPABASE_SERVICE_KEY}`,
      "Content-Type":  "application/json",
    };

    try {
      // 1. Look up the most recent order for this customer to link the invoice
      let orderId = null;
      if (email) {
        const orderRes = await fetch(
          `${env.SUPABASE_URL}/rest/v1/orders?customer_email=eq.${encodeURIComponent(email)}&order=created_at.desc&limit=1&select=id`,
          { headers: sbHeaders },
        );
        if (orderRes.ok) {
          const rows = await orderRes.json();
          orderId = rows[0]?.id || null;
        }
      }

      // 2. Insert invoices row — invoice_number is auto-generated by Supabase trigger
      const invRes = await fetch(`${env.SUPABASE_URL}/rest/v1/invoices`, {
        method:  "POST",
        headers: { ...sbHeaders, "Prefer": "return=representation" },
        body: JSON.stringify({
          order_id:       orderId,
          customer_name:  name || email || "Unknown",
          amount:         parseFloat(amountPaid),
          status:         "paid",
          issue_date:     today,
          due_date:       today,
          payment_method: "Stripe",
        }),
      });
      if (!invRes.ok) {
        const txt = await invRes.text();
        console.error(`Supabase invoices insert error ${invRes.status}: ${txt}`);
      } else {
        const invoices  = await invRes.json();
        const invoiceId = invoices[0]?.id || null;

        // 3. Insert payments row linked to the new invoice
        const payRes = await fetch(`${env.SUPABASE_URL}/rest/v1/payments`, {
          method:  "POST",
          headers: { ...sbHeaders, "Prefer": "return=minimal" },
          body: JSON.stringify({
            invoice_id: invoiceId,
            amount:     parseFloat(amountPaid),
            date:       today,
            method:     "card",
            reference:  pi.id,
            notes:      product ? `50% deposit — ${product}` : "50% deposit",
          }),
        });
        if (!payRes.ok) {
          const txt = await payRes.text();
          console.error(`Supabase payments insert error ${payRes.status}: ${txt}`);
        }
      }
    } catch (err) {
      console.error("Supabase invoice/payment insert failed:", err);
    }
  }

  // 2. Send payment confirmation email to customer (non-critical)
  if (env.RESEND_API_KEY && email) {
    try {
      await sendEmail(env.RESEND_API_KEY, {
        from:    `${BUSINESS_NAME} <${FROM_EMAIL}>`,
        to:      email,
        subject: `Deposit confirmed — ${BUSINESS_NAME}`,
        html:    depositConfirmationEmail({ name, email, amountPaid, product, cemetery }),
      });
    } catch (err) {
      console.error("Deposit confirmation email failed:", err);
    }
  }

  // 3. Notify the business (non-critical)
  if (env.RESEND_API_KEY) {
    try {
      await sendEmail(env.RESEND_API_KEY, {
        from:    `${BUSINESS_NAME} <${FROM_EMAIL}>`,
        to:      BUSINESS_EMAIL,
        subject: `Deposit received — £${amountPaid} — ${name || email}`,
        html:    depositBusinessEmail({ name, email, amountPaid, product, cemetery, piId: pi.id }),
      });
    } catch (err) {
      console.error("Deposit business email failed:", err);
    }
  }
}

// ── Email templates ─────────────────────────────────────────────────────────────
function esc(str) {
  return String(str || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function depositConfirmationEmail({ name, amountPaid, product, cemetery }) {
  const firstName = (name || "").split(" ")[0] || "there";
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F3F0;font-family:-apple-system,'DM Sans',sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F3F0;padding:24px 0;">
  <tr><td align="center">
  <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);">

    <tr><td style="background:#2C2C2C;padding:20px 28px;">
      <span style="font-family:Georgia,serif;font-size:18px;color:#fff;font-weight:normal;">Sears Melvin <span style="opacity:0.55;font-weight:300;">Memorials</span></span>
    </td></tr>

    <tr><td style="padding:32px 28px 0;">
      <div style="width:52px;height:52px;background:#4CAF50;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-bottom:20px;">
        <span style="color:white;font-size:28px;line-height:52px;display:block;text-align:center;">✓</span>
      </div>
      <h2 style="font-family:Georgia,serif;font-size:22px;color:#2C2C2C;font-weight:normal;margin:0 0 12px;">Deposit received, ${esc(firstName)}.</h2>
      <p style="color:#555;font-size:15px;line-height:1.7;margin:0 0 24px;">
        Your <strong style="color:#2C2C2C;">£${esc(amountPaid)}</strong> deposit has been received and your order is confirmed.
        We'll be in touch within 24 hours to discuss the next steps.
      </p>
    </td></tr>

    <tr><td style="padding:0 28px 28px;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F3F0;border-radius:8px;overflow:hidden;">
        <tr><td style="padding:16px 20px;">
          <div style="font-size:10px;letter-spacing:0.1em;text-transform:uppercase;color:#8B7355;font-weight:700;margin-bottom:10px;">Order summary</div>
          <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;">
            ${product  ? `<tr><td style="color:#999;padding:4px 0;width:120px;">Memorial</td><td style="color:#1A1A1A;padding:4px 0;">${esc(product)}</td></tr>` : ""}
            ${cemetery ? `<tr><td style="color:#999;padding:4px 0;">Cemetery</td><td style="color:#1A1A1A;padding:4px 0;">${esc(cemetery)}</td></tr>` : ""}
            <tr><td style="color:#999;padding:8px 0 4px;border-top:1px solid #ddd;">Deposit paid</td><td style="color:#2C2C2C;font-weight:700;padding:8px 0 4px;border-top:1px solid #ddd;">£${esc(amountPaid)}</td></tr>
          </table>
        </td></tr>
      </table>
    </td></tr>

    <tr><td style="background:#F5F3F0;border-top:1px solid #E0DCD5;padding:14px 28px;text-align:center;">
      <span style="font-size:11px;color:#BBB;">Sears Melvin Memorials &middot; <a href="mailto:${BUSINESS_EMAIL}" style="color:#BBB;">${BUSINESS_EMAIL}</a> &middot; 01268 208 559</span>
    </td></tr>

  </table>
  </td></tr>
</table>
</body></html>`;
}

function depositBusinessEmail({ name, email, amountPaid, product, cemetery, piId }) {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#F5F3F0;font-family:-apple-system,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F3F0;padding:24px 0;">
  <tr><td align="center">
  <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);">
    <tr><td style="background:#2C2C2C;padding:18px 28px;">
      <table width="100%" cellpadding="0" cellspacing="0"><tr>
        <td><span style="font-family:Georgia,serif;font-size:18px;color:#fff;">Sears Melvin <span style="opacity:0.55;">Memorials</span></span></td>
        <td align="right"><span style="background:#4CAF50;color:#fff;padding:4px 11px;border-radius:3px;font-size:11px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;">Deposit Paid</span></td>
      </tr></table>
    </td></tr>
    <tr><td style="padding:24px 28px;">
      <h2 style="font-family:Georgia,serif;font-size:20px;color:#2C2C2C;font-weight:normal;margin:0 0 16px;">Deposit Received — £${esc(amountPaid)}</h2>
      <table width="100%" cellpadding="0" cellspacing="0" style="font-size:13px;">
        <tr><td style="color:#999;padding:5px 0;width:130px;">Customer</td><td style="color:#1A1A1A;font-weight:600;">${esc(name || "—")}</td></tr>
        <tr><td style="color:#999;padding:5px 0;">Email</td><td><a href="mailto:${esc(email)}" style="color:#8B7355;">${esc(email || "—")}</a></td></tr>
        ${product  ? `<tr><td style="color:#999;padding:5px 0;">Memorial</td><td style="color:#1A1A1A;">${esc(product)}</td></tr>` : ""}
        ${cemetery ? `<tr><td style="color:#999;padding:5px 0;">Cemetery</td><td style="color:#1A1A1A;">${esc(cemetery)}</td></tr>` : ""}
        <tr><td style="color:#999;padding:5px 0;">Amount</td><td style="color:#1A1A1A;font-weight:700;">£${esc(amountPaid)}</td></tr>
        <tr><td style="color:#999;padding:5px 0;font-size:11px;">Stripe PI</td><td style="color:#AAA;font-size:11px;">${esc(piId || "—")}</td></tr>
      </table>
    </td></tr>
    <tr><td style="background:#F5F3F0;border-top:1px solid #E0DCD5;padding:12px 28px;text-align:center;">
      <span style="font-size:11px;color:#BBB;">Sears Melvin Memorials &middot; ${BUSINESS_EMAIL}</span>
    </td></tr>
  </table>
  </td></tr>
</table>
</body></html>`;
}

async function sendEmail(apiKey, { from, to, subject, html }) {
  const res = await fetch("https://api.resend.com/emails", {
    method:  "POST",
    headers: { "Authorization": `Bearer ${apiKey}`, "Content-Type": "application/json" },
    body:    JSON.stringify({ from, to, subject, html }),
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Resend ${res.status}: ${body}`);
  }
}
